version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Load environment variables from .env file
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules